// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernPaySystem.Module.Transaction.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModernPaySystem.Module.Transaction.Infrastructure.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20260705110515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.InputValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestTemplateValuesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestTemplateValuesId", "Key", "Value")
                        .HasDatabaseName("IX_InputValue_Lookup");

                    b.ToTable("InputValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FirstTransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestTemplateValuesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("CurrentTransactionId");

                    b.HasIndex("FirstTransactionId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ResponseId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestAttachment", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("RequestId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("RequestAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_RequestAuditLogs_Action");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RequestAuditLogs_UserId");

                    b.HasIndex("RequestId", "Timestamp")
                        .HasDatabaseName("IX_RequestAuditLogs_RequestId_Timestamp");

                    b.ToTable("RequestAuditLogs");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TargetRequestId");

                    b.HasIndex("SourceRequestId", "TargetRequestId", "RelationType")
                        .IsUnique();

                    b.ToTable("RequestRelations", (string)null);
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTemplateValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_RequestTemplateValues_RequestId");

                    b.HasIndex("TemplateId");

                    b.ToTable("RequestTemplateValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("CurrentUserHolderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentUserHolderId");

                    b.HasIndex("ParentTransactionId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestTransactions");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransactionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("RequestTransactionId");

                    b.ToTable("RequestTransactionAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RespondedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.ResponseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ResponseId");

                    b.ToTable("ResponseAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentAsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("DefaultReceiverDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequireAttachments")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateDescription")
                        .HasColumnType("text");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefaultReceiverDepartmentId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.TemplateDepartmentOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateDepartmentOwnerships");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.UserTemplateOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTemplateOwnerships");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SafeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentHeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MaterializedPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentHeadId")
                        .IsUnique();

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.DepartmentTemplateNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("LastRequestNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TemplateId");

                    b.ToTable("DepartmentTemplateNumber");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.LookUpField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FiledName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("LookUpFields");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.LookUpFiledValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LookUpFiledId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LookUpFiledId");

                    b.ToTable("LookUpFiledValues");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SubSystem")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PermissionEntity");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.SubSystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("SubSystem")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SubSystemUser");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HeadedDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDepartmentHead")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubSystemUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RequestId");

                    b.HasIndex("SubSystemUserId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("PermissionEntityRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionEntityRole");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("TemplateUser", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitedByUsersId")
                        .HasColumnType("uuid");

                    b.HasKey("TemplateId", "VisitedByUsersId");

                    b.HasIndex("VisitedByUsersId");

                    b.ToTable("UserVisitedTemplates", (string)null);
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.InputValue", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTemplateValues", "RequestTemplateValues")
                        .WithMany("InputValues")
                        .HasForeignKey("RequestTemplateValuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestTemplateValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Request", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", "CurrentTransaction")
                        .WithMany()
                        .HasForeignKey("CurrentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", "FirstTransaction")
                        .WithMany()
                        .HasForeignKey("FirstTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Response", "Response")
                        .WithOne("Request")
                        .HasForeignKey("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "ResponseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", null)
                        .WithMany("Requests")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Approver");

                    b.Navigation("CurrentTransaction");

                    b.Navigation("FirstTransaction");

                    b.Navigation("Requester");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "Request")
                        .WithMany("RequestAttachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestAuditLog", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestRelation", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "SourceRequest")
                        .WithMany("OutgoingRelations")
                        .HasForeignKey("SourceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "TargetRequest")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("TargetRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceRequest");

                    b.Navigation("TargetRequest");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTemplateValues", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "Request")
                        .WithOne("RequestTemplateValues")
                        .HasForeignKey("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTemplateValues", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.User", "CurrentUserHolder")
                        .WithMany()
                        .HasForeignKey("CurrentUserHolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", "ParentTransaction")
                        .WithMany("ChildTransactions")
                        .HasForeignKey("ParentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentUserHolder");

                    b.Navigation("ParentTransaction");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransactionAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", "RequestTransaction")
                        .WithMany("RequestTransactionAttachments")
                        .HasForeignKey("RequestTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("RequestTransaction");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.ResponseAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Response", "Response")
                        .WithMany("ResponseAttachments")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Template", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Department", "DefaultReceiverDepartment")
                        .WithMany()
                        .HasForeignKey("DefaultReceiverDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultReceiverDepartment");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.TemplateDepartmentOwnership", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", "Template")
                        .WithMany("DepartmentOwnerships")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.UserTemplateOwnership", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", "Template")
                        .WithMany("UserOwnerships")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.Department", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.User", "DepartmentHead")
                        .WithOne("HeadedDepartment")
                        .HasForeignKey("ModernPaySystem.SharedKernel.Domain.Entities.Department", "DepartmentHeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId");

                    b.Navigation("DepartmentHead");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.DepartmentTemplateNumber", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", null)
                        .WithMany("DepartmentTemplateNumbers")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.LookUpField", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", null)
                        .WithMany("LookUpFields")
                        .HasForeignKey("TemplateId");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.LookUpFiledValues", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.LookUpField", "LookUpFiled")
                        .WithMany("LookUpFiledValues")
                        .HasForeignKey("LookUpFiledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookUpFiled");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.User", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", null)
                        .WithMany("ReadOnlyUsers")
                        .HasForeignKey("RequestId");

                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.SubSystemUser", "SubSystemUser")
                        .WithOne("User")
                        .HasForeignKey("ModernPaySystem.SharedKernel.Domain.Entities.User", "SubSystemUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("SubSystemUser");
                });

            modelBuilder.Entity("PermissionEntityRole", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TemplateUser", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("VisitedByUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Request", b =>
                {
                    b.Navigation("IncomingRelations");

                    b.Navigation("OutgoingRelations");

                    b.Navigation("ReadOnlyUsers");

                    b.Navigation("RequestAttachments");

                    b.Navigation("RequestTemplateValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTemplateValues", b =>
                {
                    b.Navigation("InputValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", b =>
                {
                    b.Navigation("ChildTransactions");

                    b.Navigation("RequestTransactionAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Response", b =>
                {
                    b.Navigation("Request");

                    b.Navigation("ResponseAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Template", b =>
                {
                    b.Navigation("DepartmentOwnerships");

                    b.Navigation("DepartmentTemplateNumbers");

                    b.Navigation("LookUpFields");

                    b.Navigation("Requests");

                    b.Navigation("UserOwnerships");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.LookUpField", b =>
                {
                    b.Navigation("LookUpFiledValues");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.SubSystemUser", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.User", b =>
                {
                    b.Navigation("HeadedDepartment");
                });
#pragma warning restore 612, 618
        }
    }
}
