// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernPaySystem.Module.Transaction.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModernPaySystem.Module.Transaction.Infrastructure.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    partial class TransactionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.InputValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestTemplateValuesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestTemplateValuesId", "Key", "Value")
                        .HasDatabaseName("IX_InputValue_Lookup");

                    b.ToTable("InputValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FirstTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReadOnlyUsers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RequestNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestTemplateValuesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTransactionId");

                    b.HasIndex("FirstTransactionId");

                    b.HasIndex("ResponseId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestAttachment", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("RequestId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("RequestAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_RequestAuditLogs_Action");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RequestAuditLogs_UserId");

                    b.HasIndex("RequestId", "Timestamp")
                        .HasDatabaseName("IX_RequestAuditLogs_RequestId_Timestamp");

                    b.ToTable("RequestAuditLogs");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TargetRequestId");

                    b.HasIndex("SourceRequestId", "TargetRequestId", "RelationType")
                        .IsUnique();

                    b.ToTable("RequestRelations", (string)null);
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTemplateValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_RequestTemplateValues_RequestId");

                    b.HasIndex("TemplateId");

                    b.ToTable("RequestTemplateValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("CurrentUserHolderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentTransactionId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestTransactions");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransactionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("RequestTransactionId");

                    b.ToTable("RequestTransactionAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RespondedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.ResponseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ResponseId");

                    b.ToTable("ResponseAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentAsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("DefaultReceiverDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequireAttachments")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateDescription")
                        .HasColumnType("text");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.TemplateDepartmentOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateDepartmentOwnerships");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.UserTemplateOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("UserTemplateOwnerships");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SafeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.LookUpField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FiledName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("LookUpFields");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.LookUpFiledValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LookUpFiledId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LookUpFiledId");

                    b.ToTable("LookUpFiledValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.InputValue", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTemplateValues", "RequestTemplateValues")
                        .WithMany("InputValues")
                        .HasForeignKey("RequestTemplateValuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestTemplateValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Request", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", "CurrentTransaction")
                        .WithMany()
                        .HasForeignKey("CurrentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", "FirstTransaction")
                        .WithMany()
                        .HasForeignKey("FirstTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Response", "Response")
                        .WithOne("Request")
                        .HasForeignKey("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "ResponseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", null)
                        .WithMany("Requests")
                        .HasForeignKey("TemplateId");

                    b.Navigation("CurrentTransaction");

                    b.Navigation("FirstTransaction");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "Request")
                        .WithMany("RequestAttachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestAuditLog", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestRelation", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "SourceRequest")
                        .WithMany("OutgoingRelations")
                        .HasForeignKey("SourceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "TargetRequest")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("TargetRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceRequest");

                    b.Navigation("TargetRequest");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTemplateValues", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "Request")
                        .WithOne("RequestTemplateValues")
                        .HasForeignKey("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTemplateValues", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", "ParentTransaction")
                        .WithMany("ChildTransactions")
                        .HasForeignKey("ParentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTransaction");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransactionAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", "RequestTransaction")
                        .WithMany("RequestTransactionAttachments")
                        .HasForeignKey("RequestTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("RequestTransaction");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.ResponseAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Response", "Response")
                        .WithMany("ResponseAttachments")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.TemplateDepartmentOwnership", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", "Template")
                        .WithMany("DepartmentOwnerships")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.UserTemplateOwnership", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", "Template")
                        .WithMany("UserOwnerships")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.LookUpField", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Transaction.Domain.Entities.Template", null)
                        .WithMany("LookUpFields")
                        .HasForeignKey("TemplateId");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.LookUpFiledValues", b =>
                {
                    b.HasOne("ModernPaySystem.SharedKernel.Domain.Entities.LookUpField", "LookUpFiled")
                        .WithMany("LookUpFiledValues")
                        .HasForeignKey("LookUpFiledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookUpFiled");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Request", b =>
                {
                    b.Navigation("IncomingRelations");

                    b.Navigation("OutgoingRelations");

                    b.Navigation("RequestAttachments");

                    b.Navigation("RequestTemplateValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTemplateValues", b =>
                {
                    b.Navigation("InputValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.RequestTransaction", b =>
                {
                    b.Navigation("ChildTransactions");

                    b.Navigation("RequestTransactionAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Response", b =>
                {
                    b.Navigation("Request");

                    b.Navigation("ResponseAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Transaction.Domain.Entities.Template", b =>
                {
                    b.Navigation("DepartmentOwnerships");

                    b.Navigation("LookUpFields");

                    b.Navigation("Requests");

                    b.Navigation("UserOwnerships");
                });

            modelBuilder.Entity("ModernPaySystem.SharedKernel.Domain.Entities.LookUpField", b =>
                {
                    b.Navigation("LookUpFiledValues");
                });
#pragma warning restore 612, 618
        }
    }
}
