// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernPaySystem.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModernPaySystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520100639_AddNumberForRequest")]
    partial class AddNumberForRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GovId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NationalId")
                        .HasColumnType("uuid");

                    b.Property<string>("NationalityNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("GovId");

                    b.HasIndex("NationalId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.Gov", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Govs");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.KindShip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KindShips");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.National", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Nationals");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("KindShipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OperationServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperationStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipientClientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SumAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantClientId");

                    b.HasIndex("KindShipId");

                    b.HasIndex("OperationServiceTypeId");

                    b.HasIndex("OperationStatusId");

                    b.HasIndex("RecipientClientId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.OperationServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OperationServiceTypes");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.OperationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OperationStatuses");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SafeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentHeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MaterializedPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentHeadId")
                        .IsUnique();

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.DepartmentTemplateNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("LastRequestNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("DepartmentId", "TemplateId")
                        .IsUnique();

                    b.ToTable("DepartmentTemplateNumbers");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.LookUpField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FiledName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("LookUpFields");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.LookUpFiledValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LookUpFiledId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LookUpFiledId");

                    b.ToTable("LookUpFiledValues");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SubSystem")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.SubSystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("SubSystem")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SubSystemUsers");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HeadedDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDepartmentHead")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SubSystemUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.InputValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestTemplateValuesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestTemplateValuesId", "Key", "Value")
                        .HasDatabaseName("IX_InputValue_Lookup");

                    b.ToTable("InputValue");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FirstTransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestTemplateValuesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("CurrentTransactionId");

                    b.HasIndex("FirstTransactionId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ResponseId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestAttachment", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("RequestId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("RequestAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTemplateValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_RequestTemplateValues_RequestId");

                    b.HasIndex("TemplateId");

                    b.ToTable("RequestTemplateValues");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("CurrentUserHolderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentUserHolderId");

                    b.HasIndex("ParentTransactionId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestTransactions");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTransactionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("RequestTransactionId");

                    b.ToTable("RequestTransactionAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RespondedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.ResponseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ResponseId");

                    b.ToTable("ResponseAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentAsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("DefaultReceiverDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequireAttachments")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateDescription")
                        .HasColumnType("text");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefaultReceiverDepartmentId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.TemplateDepartmentOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateOwnerships");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.UserTemplateOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTemplateOwnerships");
                });

            modelBuilder.Entity("PermissionEntityRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("RequestUser", b =>
                {
                    b.Property<Guid>("MentionedRequestsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReadOnlyUsersId")
                        .HasColumnType("uuid");

                    b.HasKey("MentionedRequestsId", "ReadOnlyUsersId");

                    b.HasIndex("ReadOnlyUsersId");

                    b.ToTable("RequestUser");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("TemplateUser", b =>
                {
                    b.Property<Guid>("VisitedByUsersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitedTemplatesId")
                        .HasColumnType("uuid");

                    b.HasKey("VisitedByUsersId", "VisitedTemplatesId");

                    b.HasIndex("VisitedTemplatesId");

                    b.ToTable("UserVisitedTemplates", (string)null);
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.Client", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.Gov", "Gov")
                        .WithMany()
                        .HasForeignKey("GovId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.National", "National")
                        .WithMany()
                        .HasForeignKey("NationalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Gov");

                    b.Navigation("National");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.Operation", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.Client", "ApplicantClient")
                        .WithMany()
                        .HasForeignKey("ApplicantClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.KindShip", "KindShip")
                        .WithMany()
                        .HasForeignKey("KindShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.OperationServiceType", "OperationServiceType")
                        .WithMany()
                        .HasForeignKey("OperationServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.OperationStatus", "Status")
                        .WithMany()
                        .HasForeignKey("OperationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.PaySystemEntities.FastOperations.Client", "RecipientClient")
                        .WithMany()
                        .HasForeignKey("RecipientClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicantClient");

                    b.Navigation("KindShip");

                    b.Navigation("OperationServiceType");

                    b.Navigation("RecipientClient");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.Department", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", "DepartmentHead")
                        .WithOne("HeadedDepartment")
                        .HasForeignKey("ModernPaySystem.Domain.Entities.SharedEntities.Department", "DepartmentHeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DepartmentHead");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.DepartmentTemplateNumber", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Department", "Department")
                        .WithMany("DepartmentTemplateNumbers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", "Template")
                        .WithMany("DepartmentTemplateNumbers")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.LookUpField", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", null)
                        .WithMany("LookUpFields")
                        .HasForeignKey("TemplateId");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.LookUpFiledValues", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.LookUpField", "LookUpFiled")
                        .WithMany("LookUpFiledValues")
                        .HasForeignKey("LookUpFiledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookUpFiled");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.SubSystemUser", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", "User")
                        .WithOne("SubSystemUser")
                        .HasForeignKey("ModernPaySystem.Domain.Entities.SharedEntities.SubSystemUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.User", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.InputValue", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTemplateValues", "RequestTemplateValues")
                        .WithMany("InputValues")
                        .HasForeignKey("RequestTemplateValuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestTemplateValues");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", "Approver")
                        .WithMany("RequestsAsApprover")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTransaction", "CurrentTransaction")
                        .WithMany()
                        .HasForeignKey("CurrentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTransaction", "FirstTransaction")
                        .WithMany()
                        .HasForeignKey("FirstTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", "Requester")
                        .WithMany("RequestsAsRequester")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Response", "Response")
                        .WithOne("Request")
                        .HasForeignKey("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", "ResponseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", null)
                        .WithMany("Requests")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Approver");

                    b.Navigation("CurrentTransaction");

                    b.Navigation("FirstTransaction");

                    b.Navigation("Requester");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Attachment", "Attachment")
                        .WithMany("RequestAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", "Request")
                        .WithMany("RequestAttachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTemplateValues", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", "Request")
                        .WithOne("RequestTemplateValues")
                        .HasForeignKey("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTemplateValues", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTransaction", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", "CurrentUserHolder")
                        .WithMany()
                        .HasForeignKey("CurrentUserHolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTransaction", "ParentTransaction")
                        .WithMany("ChildTransactions")
                        .HasForeignKey("ParentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentUserHolder");

                    b.Navigation("ParentTransaction");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTransactionAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTransaction", "RequestTransaction")
                        .WithMany("RequestTransactionAttachments")
                        .HasForeignKey("RequestTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("RequestTransaction");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.ResponseAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Attachment", "Attachment")
                        .WithMany("ResponseAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Response", "Response")
                        .WithMany("ResponseAttachments")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Department", "DefaultReceiverDepartment")
                        .WithMany()
                        .HasForeignKey("DefaultReceiverDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultReceiverDepartment");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.TemplateDepartmentOwnership", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Department", "Department")
                        .WithMany("TemplateOwnerships")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", "Template")
                        .WithMany("DepartmentOwnerships")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.UserTemplateOwnership", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", "Template")
                        .WithMany("UserOwnerships")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", "User")
                        .WithMany("TemplateOwnerships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermissionEntityRole", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestUser", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", null)
                        .WithMany()
                        .HasForeignKey("MentionedRequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", null)
                        .WithMany()
                        .HasForeignKey("ReadOnlyUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TemplateUser", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", null)
                        .WithMany()
                        .HasForeignKey("VisitedByUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", null)
                        .WithMany()
                        .HasForeignKey("VisitedTemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.Attachment", b =>
                {
                    b.Navigation("RequestAttachments");

                    b.Navigation("ResponseAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("DepartmentTemplateNumbers");

                    b.Navigation("TemplateOwnerships");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.LookUpField", b =>
                {
                    b.Navigation("LookUpFiledValues");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.User", b =>
                {
                    b.Navigation("HeadedDepartment")
                        .IsRequired();

                    b.Navigation("RequestsAsApprover");

                    b.Navigation("RequestsAsRequester");

                    b.Navigation("SubSystemUser");

                    b.Navigation("TemplateOwnerships");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", b =>
                {
                    b.Navigation("RequestAttachments");

                    b.Navigation("RequestTemplateValues");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTemplateValues", b =>
                {
                    b.Navigation("InputValues");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestTransaction", b =>
                {
                    b.Navigation("ChildTransactions");

                    b.Navigation("RequestTransactionAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Response", b =>
                {
                    b.Navigation("Request");

                    b.Navigation("ResponseAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", b =>
                {
                    b.Navigation("DepartmentOwnerships");

                    b.Navigation("DepartmentTemplateNumbers");

                    b.Navigation("LookUpFields");

                    b.Navigation("Requests");

                    b.Navigation("UserOwnerships");
                });
#pragma warning restore 612, 618
        }
    }
}
