// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernPaySystem.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModernPaySystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SafeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.LookUpField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FiledName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("LookUpFields");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.LookUpFiledValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LookUpFiledId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LookUpFiledId");

                    b.ToTable("LookUpFiledValues");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SubSystem")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.SubSystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("SubSystem")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SubSystemUsers");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubSystemUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentAsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ResponseId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestAttachment", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("RequestId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("RequestAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RespondedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.ResponseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ResponseId");

                    b.ToTable("ResponseAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentAsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("TemplateDescription")
                        .HasColumnType("text");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.TemplateOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("TemplateOwnerships");
                });

            modelBuilder.Entity("PermissionEntityRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.LookUpField", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", null)
                        .WithMany("LookUpFields")
                        .HasForeignKey("TemplateId");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.LookUpFiledValues", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.LookUpField", "LookUpFiled")
                        .WithMany("LookUpFiledValues")
                        .HasForeignKey("LookUpFiledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookUpFiled");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.SubSystemUser", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", "User")
                        .WithOne("SubSystemUser")
                        .HasForeignKey("ModernPaySystem.Domain.Entities.SharedEntities.SubSystemUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", "Approver")
                        .WithMany("RequestsAsApprover")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", "Requester")
                        .WithMany("RequestsAsRequester")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Response", "Response")
                        .WithOne("Request")
                        .HasForeignKey("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", "ResponseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", "Template")
                        .WithMany("Requests")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Requester");

                    b.Navigation("Response");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.RequestAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Attachment", "Attachment")
                        .WithMany("RequestAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", "Request")
                        .WithMany("RequestAttachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.ResponseAttachment", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Attachment", "Attachment")
                        .WithMany("ResponseAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Response", "Response")
                        .WithMany("ResponseAttachments")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.TemplateOwnership", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", "Template")
                        .WithMany("Ownerships")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", "User")
                        .WithMany("TemplateOwnerships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermissionEntityRole", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Domain.Entities.SharedEntities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.Attachment", b =>
                {
                    b.Navigation("RequestAttachments");

                    b.Navigation("ResponseAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.LookUpField", b =>
                {
                    b.Navigation("LookUpFiledValues");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.SharedEntities.User", b =>
                {
                    b.Navigation("RequestsAsApprover");

                    b.Navigation("RequestsAsRequester");

                    b.Navigation("SubSystemUser");

                    b.Navigation("TemplateOwnerships");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Request", b =>
                {
                    b.Navigation("RequestAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Response", b =>
                {
                    b.Navigation("Request");

                    b.Navigation("ResponseAttachments");
                });

            modelBuilder.Entity("ModernPaySystem.Domain.Entities.TransactionSystemEntities.Template", b =>
                {
                    b.Navigation("LookUpFields");

                    b.Navigation("Ownerships");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
