// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernPaySystem.Module.Archive.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModernPaySystem.Module.Archive.Infrastructure.Migrations
{
    [DbContext(typeof(ArchiveDbContext))]
    [Migration("20260718121434_AddDepartmentIdToFolderPermissions")]
    partial class AddDepartmentIdToFolderPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("ArchiveRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_ArchiveAuditLogs_Action");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ArchiveAuditLogs_UserId");

                    b.HasIndex("ArchiveRecordId", "Timestamp")
                        .HasDatabaseName("IX_ArchiveAuditLogs_ArchiveRecordId_Timestamp");

                    b.ToTable("ArchiveAuditLogs");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedFileExtensions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DefaultPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ArchiveConfigs");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveFormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentAsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("FormDescription")
                        .HasColumnType("text");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DynamicForms");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedByRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchiveRecordTemplateValues")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FormId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("FormId");

                    b.ToTable("ArchiveRecords");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecordFormInputValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchiveRecordTemplateValuesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveRecordTemplateValuesId");

                    b.ToTable("ArchiveRecordFormInputValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecordTemplateValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchiveFormTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchiveRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveFormTemplateId");

                    b.HasIndex("ArchiveRecordId")
                        .IsUnique();

                    b.ToTable("ArchiveRecordTemplateValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.DeleteArchiveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivitySnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DependenciesSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExecutedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequesterNotificationMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequesterNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("SourceFolderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "TargetType", "TargetId", "Status");

                    b.ToTable("DeleteArchiveRequests");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.DepartmentArchiveLeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "UserId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("DepartmentArchiveLeaders");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchiveRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("PhysicalFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveRecordId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FileType");

                    b.HasIndex("PhysicalFileId");

                    b.HasIndex("SourceType");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.EditArchiveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchiveRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RequestedChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RequestedFileDeletionIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("RequestedRecordName")
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveRecordId");

                    b.HasIndex("DepartmentId", "ArchiveRecordId", "Status");

                    b.ToTable("EditArchiveRequests");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("DefaultStoragePath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IconId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.FolderIcon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SvgContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FolderIcons");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.FolderPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsInherited")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FolderId");

                    b.ToTable("FolderPermissions");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.PhysicalFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchiveRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("EditArchiveRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQrPage")
                        .HasColumnType("boolean");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EditArchiveRequestId");

                    b.HasIndex("ArchiveRecordId", "CreatedAt")
                        .HasDatabaseName("IX_PhysicalFiles_ArchiveRecordId_CreatedAt");

                    b.HasIndex("ArchiveRecordId", "IsDeleted", "FileExtension")
                        .HasDatabaseName("IX_PhysicalFiles_ArchiveRecordId_IsDeleted_FileExtension_Covering");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ArchiveRecordId", "IsDeleted", "FileExtension"), new[] { "FileSize", "ContentType", "FileName", "CreatedAt", "UpdatedAt" });

                    b.ToTable("PhysicalFiles");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveAuditLog", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecord", "ArchiveRecord")
                        .WithMany()
                        .HasForeignKey("ArchiveRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveRecord");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecord", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.Folder", "Folder")
                        .WithMany("ArchiveRecords")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveFormTemplate", "Form")
                        .WithMany("ArchiveRecords")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Folder");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecordFormInputValue", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecordTemplateValues", null)
                        .WithMany("ArchiveRecordFormInputValues")
                        .HasForeignKey("ArchiveRecordTemplateValuesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecordTemplateValues", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveFormTemplate", "ArchiveFormTemplate")
                        .WithMany()
                        .HasForeignKey("ArchiveFormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecord", "ArchiveRecord")
                        .WithOne("ArchiveRecordTemplateValuesId")
                        .HasForeignKey("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecordTemplateValues", "ArchiveRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveFormTemplate");

                    b.Navigation("ArchiveRecord");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.Document", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecord", "ArchiveRecord")
                        .WithMany()
                        .HasForeignKey("ArchiveRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.PhysicalFile", "PhysicalFile")
                        .WithMany()
                        .HasForeignKey("PhysicalFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ArchiveRecord");

                    b.Navigation("PhysicalFile");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.EditArchiveRequest", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecord", "ArchiveRecord")
                        .WithMany()
                        .HasForeignKey("ArchiveRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveRecord");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.Folder", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.FolderIcon", "Icon")
                        .WithMany("Folders")
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.Folder", "Parent")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Icon");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.FolderPermission", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.Folder", "Folder")
                        .WithMany("Permissions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.PhysicalFile", b =>
                {
                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecord", "ArchiveRecord")
                        .WithMany("PhysicalFiles")
                        .HasForeignKey("ArchiveRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModernPaySystem.Module.Archive.Domain.Entities.EditArchiveRequest", "EditArchiveRequest")
                        .WithMany("PhysicalFiles")
                        .HasForeignKey("EditArchiveRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArchiveRecord");

                    b.Navigation("EditArchiveRequest");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveFormTemplate", b =>
                {
                    b.Navigation("ArchiveRecords");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecord", b =>
                {
                    b.Navigation("ArchiveRecordTemplateValuesId");

                    b.Navigation("PhysicalFiles");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.ArchiveRecordTemplateValues", b =>
                {
                    b.Navigation("ArchiveRecordFormInputValues");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.EditArchiveRequest", b =>
                {
                    b.Navigation("PhysicalFiles");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.Folder", b =>
                {
                    b.Navigation("ArchiveRecords");

                    b.Navigation("Permissions");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("ModernPaySystem.Module.Archive.Domain.Entities.FolderIcon", b =>
                {
                    b.Navigation("Folders");
                });
#pragma warning restore 612, 618
        }
    }
}
