export const queryKeys = {
    department: {
        all: ['departments'] as const,
        lists: () => [...queryKeys.department.all, 'list'] as const,
        list: (filters?: any) => [...queryKeys.department.lists(), filters] as const,
        details: () => [...queryKeys.department.all, 'detail'] as const,
        detail: (id: string | null) => [...queryKeys.department.details(), id] as const,
        tree: (rootId?: string, mode?: string) => [...queryKeys.department.all, 'tree', rootId, mode] as const,
    },
    user: {
        all: ['users'] as const,
        lists: () => [...queryKeys.user.all, 'list'] as const,
        list: (filters?: any) => [...queryKeys.user.lists(), filters] as const,
        details: () => [...queryKeys.user.all, 'detail'] as const,
        detail: (id: string | null) => [...queryKeys.user.details(), id] as const,
        visitedTemplates: () => [...queryKeys.user.all, 'visited-templates'] as const,
    },
    template: {
        all: ['templates'] as const,
        lists: () => [...queryKeys.template.all, 'list'] as const,
        list: (filters?: any) => [...queryKeys.template.lists(), filters] as const,
        details: () => [...queryKeys.template.all, 'detail'] as const,
        detail: (id: string | null) => [...queryKeys.template.details(), id] as const,
        ownerships: (id: string) => [...queryKeys.template.detail(id), 'ownerships'] as const,
        userOwnerships: (id: string) => [...queryKeys.template.detail(id), 'userOwnerships'] as const,
        byDepartment: (departmentId: string) => [...queryKeys.template.all, 'byDepartment', departmentId] as const,
        byUser: (userId: string) => [...queryKeys.template.all, 'byUser', userId] as const,
    },
    form: {
        all: ['forms'] as const,
        lists: () => [...queryKeys.form.all, 'list'] as const,
        list: (filters: any) => [...queryKeys.form.lists(), filters] as const,
        details: () => [...queryKeys.form.all, 'detail'] as const,
        detail: (id: string | null) => [...queryKeys.form.details(), id] as const,
        responses: (id: string | null) => [...queryKeys.form.detail(id), 'responses'] as const,
        transactions: (id: string | null) => [...queryKeys.form.detail(id), 'transactions'] as const,
    },
    contract: {
        all: ['contracts'] as const,
        lists: () => [...queryKeys.contract.all, 'list'] as const,
        list: (filters: any) => [...queryKeys.contract.lists(), filters] as const,
        details: () => [...queryKeys.contract.all, 'detail'] as const,
        detail: (id: string | number) => [...queryKeys.contract.details(), id] as const,
        byTenant: (tenantId: string | number) => [...queryKeys.contract.all, 'byTenant', tenantId] as const,
        byLessor: (lessorId: string | number) => [...queryKeys.contract.all, 'byLessor', lessorId] as const,
    },
    process: {
        all: ['processes'] as const,
        lists: () => [...queryKeys.process.all, 'list'] as const,
        list: (filters: any) => [...queryKeys.process.lists(), filters] as const,
        details: () => [...queryKeys.process.all, 'detail'] as const,
        detail: (id: string | null) => [...queryKeys.process.details(), id] as const,
    },
    lookup: {
        all: ['lookups'] as const,
        lists: () => [...queryKeys.lookup.all, 'list'] as const,
        list: (type: string) => [...queryKeys.lookup.lists(), type] as const,
        details: () => [...queryKeys.lookup.all, 'detail'] as const,
        detail: (id: string) => [...queryKeys.lookup.details(), id] as const,
    },
    delphi: {
        all: ['delphi'] as const,
        transactions: () => [...queryKeys.delphi.all, 'transactions'] as const,
        transaction: (id: string | number) => [...queryKeys.delphi.transactions(), id] as const,
    },
    archiving: {
        folders: {
            all: ['archiving', 'folders'] as const,
            lists: () => [...queryKeys.archiving.folders.all, 'list'] as const,
            list: (filters?: any) => [...queryKeys.archiving.folders.lists(), filters] as const,
            details: () => [...queryKeys.archiving.folders.all, 'detail'] as const,
            detail: (id: string | null) => [...queryKeys.archiving.folders.details(), id] as const,
        },
        records: {
            all: ['archiving', 'records'] as const,
            lists: () => [...queryKeys.archiving.records.all, 'list'] as const,
            list: (folderId: string, page?: number, pageSize?: number) => [...queryKeys.archiving.records.lists(), { folderId, page, pageSize }] as const,
            details: () => [...queryKeys.archiving.records.all, 'detail'] as const,
            detail: (id: string | null) => [...queryKeys.archiving.records.details(), id] as const,
        },
        dynamicForms: {
            all: ['archiving', 'dynamicForms'] as const,
            lists: () => [...queryKeys.archiving.dynamicForms.all, 'list'] as const,
            list: (page?: number, pageSize?: number) => [...queryKeys.archiving.dynamicForms.lists(), { page, pageSize }] as const,
            details: () => [...queryKeys.archiving.dynamicForms.all, 'detail'] as const,
            detail: (id: string | null) => [...queryKeys.archiving.dynamicForms.details(), id] as const,
        },
        editRequests: {
            all: ['archiving', 'editRequests'] as const,
            lists: () => [...queryKeys.archiving.editRequests.all, 'list'] as const,
            listPending: (departmentId: string, page: number, pageSize: number) => [...queryKeys.archiving.editRequests.lists(), 'pending', { departmentId, page, pageSize }] as const,
            listMy: (page: number, pageSize: number) => [...queryKeys.archiving.editRequests.lists(), 'my', { page, pageSize }] as const,
            details: () => [...queryKeys.archiving.editRequests.all, 'detail'] as const,
            detail: (id: string | null) => [...queryKeys.archiving.editRequests.details(), id] as const,
        },
        auditLogs: {
            all: ['archiving', 'auditLogs'] as const,
            lists: () => [...queryKeys.archiving.auditLogs.all, 'list'] as const,
            list: (filters: any) => [...queryKeys.archiving.auditLogs.lists(), filters] as const,
        },
        ledDepartments: {
            all: ['archiving', 'ledDepartments'] as const,
        },
        reports: {
            all: ['archiving', 'reports'] as const,
            myDepartments: () => [...queryKeys.archiving.reports.all, 'myDepartments'] as const,
            dashboard: () => [...queryKeys.archiving.reports.all, 'dashboard'] as const,
            daily: (date?: string | null) => [...queryKeys.archiving.reports.all, 'daily', date] as const,
            weekly: (weekStart?: string | null) => [...queryKeys.archiving.reports.all, 'weekly', weekStart] as const,
            monthly: (year?: number | null, month?: number | null) => [...queryKeys.archiving.reports.all, 'monthly', year, month] as const,
            userActivity: (fromDate?: string | null, toDate?: string | null) => [...queryKeys.archiving.reports.all, 'userActivity', fromDate, toDate] as const,
            activeUsers: (fromDate?: string | null, toDate?: string | null) => [...queryKeys.archiving.reports.all, 'activeUsers', fromDate, toDate] as const,
            storage: () => [...queryKeys.archiving.reports.all, 'storage'] as const,
            charts: (fromDate?: string | null, toDate?: string | null) => [...queryKeys.archiving.reports.all, 'charts', fromDate, toDate] as const,
        }
    }
};
